version: '3.8'

services:
  task-scheduler:
    image: bunnybunbun37204/cusw-scheduler:latest
    container_name: cusw-scheduler
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_SENDER=${EMAIL_SENDER}
    # หากต้องการใช้ .env file แทน
    # env_file:
    #   - .env
    
    # หากต้องการ expose port
    # ports:
    #   - "8080:8080"
    
    # หากต้องการ volume สำหรับ logs
    # volumes:
    #   - ./logs:/app/logs
